name: create-vsix
on: 
  pull_request:
    types: [labeled, unlabeled, synchronize]
jobs:
  create-vsix:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'create-vsix')
    steps:
      # Get a token from the ci application so we can trigger follow up work flows
      - name: Get Token From roku-ci-token Application
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Set New GitHub Token
        run: echo "TOKEN=${{ steps.generate-token.outputs.token }}" >> $GITHUB_ENV
      #trigger the build on vscode-brightscript-language
      - uses: aurelien-baudet/workflow-dispatch@v2.1.1
        id: create-vsix
        with:
         workflow: create-vsix
         ref: master
         wait-for-completion: true
         display-workflow-run-url: true
         repo: rokucommunity/vscode-brightscript-language
         token: ${{ env.TOKEN }}
         inputs: '{ "branch": "${{ github.head_ref }}"}'
      #add a comment comment on the PR with the workflow link (for the artifact link)
      - uses: actions/github-script@v5
        with:
          github-token: ${{ env.TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey there! I just built a new version of the vscode extension based on ${{ github.event.pull_request.head.sha }}. You can downloaded the .vsix [here](${{steps.create-vsix.outputs.workflow-url}}) and then follow [these installation instructions](https://github.com/rokucommunity/vscode-brightscript-language#pre-release-versions).'
            })
