name: create-vsix
on: 
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  create-vsix:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'create-vsix')
    steps:
      - run: echo "hello world"
    