name: create-vsix
on: 
  pull_request:
    types: [labeled, unlabeled, synchronize]
if: contains(github.event.pull_request.labels.*.name, 'create-vsix')
jobs:
  create-vsix:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
    