name: create-vsix
on: 
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  create-vsix:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'create-vsix')
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: create-vsix
          ref: master
          repo: rokucommunity/vscode-brightscript-language
          token: ${{ secrets.WORKFLOW_DISPATCH_PERSONAL_TOKEN }}
          inputs: '{ "branch ": "${GITHUB_REF}"}'

