name: Make Release Artifacts

on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  run:
      if: startsWith( github.head_ref, 'release/')
      uses: rokucommunity/workflows/.github/workflows/make-release-artifacts.yml@master
      with:
        branch: ${{ github.event.pull_request.head.ref }}
        node-version: "16.20.2"
        artifact-paths: "./*.tgz" # "*.vsix"
      secrets: inherit

  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"

  make-release-artifacts-success-or-skip:
    needs: [run, noop]
    runs-on: ubuntu-latest
    steps:
        - run: echo "done"
